volumes:
  local_mysql_data: {}

services:
  mysql-db:
    image: mysql:latest
    container_name: local_event_hub_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - local_mysql_data:/var/lib/mysql
    env_file:
      - .env.local

  adminer:
    image: adminer:latest
    container_name: local_event_hub_adminer
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    env_file:
      - .env.local

  mailhog:
    image: mailhog/mailhog
    container_name: local_event_hub_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
